# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIncomeCodeTable',
            fields=[
                ('accountcode', models.IntegerField(db_column='accountCode', primary_key=True, serialize=False)),
                ('accountname', models.CharField(db_column='accountName', max_length=125)),
            ],
            options={
                'db_table': 'Account_income_Code_table',
            },
        ),
        migrations.CreateModel(
            name='AccountIncomeTable',
            fields=[
                ('account_income_id', models.CharField(db_column='Account_income_ID', max_length=125, primary_key=True, serialize=False)),
                ('inputmonth', models.CharField(blank=True, db_column='inputMonth', max_length=125, null=True)),
                ('etcode', models.IntegerField(blank=True, db_column='etCode', null=True)),
                ('productcode', models.IntegerField(blank=True, db_column='productCode', null=True)),
                ('accountcode', models.IntegerField(blank=True, db_column='accountCode', null=True)),
                ('inputmoneycode', models.IntegerField(blank=True, db_column='inputMoneyCode', null=True)),
                ('confirmcode', models.IntegerField(blank=True, db_column='confirmCode', null=True)),
            ],
            options={
                'db_table': 'Account_income_table',
            },
        ),
        migrations.CreateModel(
            name='CardIncomeTable',
            fields=[
                ('card_income_id', models.CharField(db_column='Card_income_ID', max_length=125, primary_key=True, serialize=False)),
                ('inputdate', models.CharField(blank=True, db_column='inputDate', max_length=125, null=True)),
                ('etcode', models.IntegerField(blank=True, db_column='etCode', null=True)),
                ('productcode', models.IntegerField(blank=True, db_column='productCode', null=True)),
                ('cardsalenumber', models.IntegerField(blank=True, db_column='cardSaleNumber', null=True)),
                ('faceamount', models.IntegerField(blank=True, db_column='faceAmount', null=True)),
                ('totalamount', models.IntegerField(blank=True, db_column='totalAmount', null=True)),
                ('discounttotalamount', models.IntegerField(blank=True, db_column='discountTotalAmount', null=True)),
                ('confirmcode', models.IntegerField(blank=True, db_column='confirmCode', null=True)),
            ],
            options={
                'db_table': 'Card_income_table',
            },
        ),
        migrations.CreateModel(
            name='EtcodeTable',
            fields=[
                ('etcode', models.IntegerField(db_column='etCode', primary_key=True, serialize=False)),
                ('etname', models.CharField(db_column='etName', max_length=125)),
            ],
            options={
                'db_table': 'etCode_table',
            },
        ),
        migrations.CreateModel(
            name='NoticeIncomeCodeTable',
            fields=[
                ('noticeincomecode', models.IntegerField(db_column='NoticeIncomeCode', primary_key=True, serialize=False)),
                ('noticeincomename', models.CharField(db_column='NoticeIncomeName', max_length=125)),
            ],
            options={
                'db_table': 'Notice_income_Code_table',
            },
        ),
        migrations.CreateModel(
            name='NoticeIncomeTable',
            fields=[
                ('notice_income_id', models.CharField(db_column='Notice_income_ID', max_length=125, primary_key=True, serialize=False)),
                ('bussinesscollectiondate', models.CharField(blank=True, db_column='bussinessCollectionDate', max_length=125, null=True)),
                ('etcode', models.IntegerField(blank=True, db_column='etCode', null=True)),
                ('productcode', models.IntegerField(blank=True, db_column='productCode', null=True)),
                ('noticeincomecode', models.IntegerField(blank=True, db_column='NoticeIncomeCode', null=True)),
                ('bussinessincomeamount', models.IntegerField(blank=True, db_column='bussinessIncomeAmount', null=True)),
                ('confirmcode', models.IntegerField(blank=True, db_column='confirmCode', null=True)),
            ],
            options={
                'db_table': 'Notice_income_table',
            },
        ),
        migrations.CreateModel(
            name='PayeeusecodeTable',
            fields=[
                ('payeeusecode', models.IntegerField(db_column='payeeUseCode', primary_key=True, serialize=False)),
                ('payeeusename', models.CharField(db_column='payeeUseName', max_length=125)),
            ],
            options={
                'db_table': 'payeeUseCode_table',
            },
        ),
        migrations.CreateModel(
            name='ProductCodeTable',
            fields=[
                ('productcode', models.CharField(db_column='productCode', max_length=125, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productName', max_length=125)),
                ('whetheruser', models.CharField(blank=True, db_column='whetherUser', max_length=125, null=True)),
                ('whetheraccount', models.CharField(blank=True, db_column='whetherAccount', max_length=125, null=True)),
                ('whethercard', models.CharField(blank=True, db_column='whetherCard', max_length=125, null=True)),
                ('whethersettlement', models.CharField(blank=True, db_column='whetherSettlement', max_length=125, null=True)),
                ('whetherretained', models.CharField(blank=True, db_column='whetherRetained', max_length=125, null=True)),
                ('whethernotice', models.CharField(blank=True, db_column='whetherNotice', max_length=125, null=True)),
            ],
            options={
                'db_table': 'Product_Code_Table',
            },
        ),
        migrations.CreateModel(
            name='RetainedIncomeTable',
            fields=[
                ('retained_income_id', models.CharField(db_column='Retained_income_ID', max_length=125, primary_key=True, serialize=False)),
                ('writeoffdate', models.CharField(blank=True, db_column='writeOffDate', max_length=125, null=True)),
                ('etcode', models.IntegerField(blank=True, db_column='etCode', null=True)),
                ('productcode', models.IntegerField(blank=True, db_column='productCode', null=True)),
                ('writeofftypecode', models.IntegerField(blank=True, db_column='writeOffTypeCode', null=True)),
                ('writeoffamount', models.IntegerField(blank=True, db_column='writeOffAmount', null=True)),
                ('confirmcode', models.IntegerField(blank=True, db_column='confirmCode', null=True)),
            ],
            options={
                'db_table': 'Retained_income_table',
            },
        ),
        migrations.CreateModel(
            name='SetBetweenNetworksTable',
            fields=[
                ('set_between_networks_id', models.CharField(db_column='Set_between_networks_ID', max_length=125, primary_key=True, serialize=False)),
                ('settlementmonth', models.CharField(blank=True, db_column='settlementMonth', max_length=125, null=True)),
                ('etcode', models.IntegerField(blank=True, db_column='etCode', null=True)),
                ('productcode', models.IntegerField(blank=True, db_column='productCode', null=True)),
                ('settlementoperatorcode', models.IntegerField(blank=True, db_column='settlementOperatorCode', null=True)),
                ('settlementtypecode', models.IntegerField(blank=True, db_column='settlementTypeCode', null=True)),
                ('settlementamount', models.IntegerField(blank=True, db_column='settlementAmount', null=True)),
                ('confirmcode', models.IntegerField(blank=True, db_column='confirmCode', null=True)),
            ],
            options={
                'db_table': 'Set_between_networks_table',
            },
        ),
        migrations.CreateModel(
            name='SettlementoperatorcodeTable',
            fields=[
                ('settlementoperatorcode', models.IntegerField(db_column='settlementOperatorCode', primary_key=True, serialize=False)),
                ('settlementoperatorname', models.CharField(db_column='settlementOperatorName', max_length=125)),
            ],
            options={
                'db_table': 'settlementOperatorCode_table',
            },
        ),
        migrations.CreateModel(
            name='SettlementtypecodeTable',
            fields=[
                ('settlementtypecode', models.IntegerField(db_column='settlementTypeCode', primary_key=True, serialize=False)),
                ('settlementtypename', models.CharField(db_column='settlementTypeName', max_length=125)),
            ],
            options={
                'db_table': 'settlementTypeCode_table',
            },
        ),
        migrations.CreateModel(
            name='WriteofftypecodeTable',
            fields=[
                ('writeofftypecode', models.IntegerField(db_column='writeOffTypeCode', primary_key=True, serialize=False)),
                ('writeofftypename', models.CharField(db_column='writeOffTypeName', max_length=125)),
            ],
            options={
                'db_table': 'writeOffTypeCode_table',
            },
        ),
    ]
